"""initial schema (rebuild)

Revision ID: 0001_rebuild_initial
Revises: 
Create Date: 2026-08-16 17:14:31.807918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_rebuild_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('picture_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rule', sa.String(length=32), nullable=False),
    sa.Column('gmail_label_id', sa.String(length=120), nullable=True),
    sa.Column('is_needs_review', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_categories_user_name')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('gmail_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('google_email', sa.String(length=320), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_accounts_user_id'), 'gmail_accounts', ['user_id'], unique=True)
    op.create_table('inbox_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_inbox_threads', sa.Integer(), nullable=False),
    sa.Column('unread', sa.Integer(), nullable=False),
    sa.Column('oldest_days', sa.Integer(), nullable=False),
    sa.Column('top_senders_json', sa.JSON(), nullable=False),
    sa.Column('category_tab_counts_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_snapshots_user_id'), 'inbox_snapshots', ['user_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('chunk_limit', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('threads_decided', sa.Integer(), nullable=False),
    sa.Column('counts_json', sa.JSON(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('fallback_events', sa.Integer(), nullable=False),
    sa.Column('interrupt_reason', sa.Text(), nullable=True),
    sa.Column('undone_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_user_id'), 'runs', ['user_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('was_fallback', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_run_id'), 'llm_calls', ['run_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_user_id'), 'llm_calls', ['user_id'], unique=False)
    op.create_table('mutations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('label_name', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('undone_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mutations_gmail_thread_id'), 'mutations', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_mutations_run_id'), 'mutations', ['run_id'], unique=False)
    op.create_index(op.f('ix_mutations_user_id'), 'mutations', ['user_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_run_events_run_seq')
    )
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_events_user_id'), 'run_events', ['user_id'], unique=False)
    op.create_table('sender_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sender_address', sa.String(length=320), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_from', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sender_address', name='uq_sender_profiles_user_sender')
    )
    op.create_index(op.f('ix_sender_profiles_category_id'), 'sender_profiles', ['category_id'], unique=False)
    op.create_index(op.f('ix_sender_profiles_user_id'), 'sender_profiles', ['user_id'], unique=False)
    op.create_table('thread_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=64), nullable=False),
    sa.Column('sender', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=1000), nullable=False),
    sa.Column('snippet', sa.String(length=500), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gmail_thread_id', name='uq_thread_decisions_user_thread')
    )
    op.create_index(op.f('ix_thread_decisions_category_id'), 'thread_decisions', ['category_id'], unique=False)
    op.create_index(op.f('ix_thread_decisions_gmail_thread_id'), 'thread_decisions', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_thread_decisions_run_id'), 'thread_decisions', ['run_id'], unique=False)
    op.create_index(op.f('ix_thread_decisions_user_id'), 'thread_decisions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_decisions_user_id'), table_name='thread_decisions')
    op.drop_index(op.f('ix_thread_decisions_run_id'), table_name='thread_decisions')
    op.drop_index(op.f('ix_thread_decisions_gmail_thread_id'), table_name='thread_decisions')
    op.drop_index(op.f('ix_thread_decisions_category_id'), table_name='thread_decisions')
    op.drop_table('thread_decisions')
    op.drop_index(op.f('ix_sender_profiles_user_id'), table_name='sender_profiles')
    op.drop_index(op.f('ix_sender_profiles_category_id'), table_name='sender_profiles')
    op.drop_table('sender_profiles')
    op.drop_index(op.f('ix_run_events_user_id'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_mutations_user_id'), table_name='mutations')
    op.drop_index(op.f('ix_mutations_run_id'), table_name='mutations')
    op.drop_index(op.f('ix_mutations_gmail_thread_id'), table_name='mutations')
    op.drop_table('mutations')
    op.drop_index(op.f('ix_llm_calls_user_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_run_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_runs_user_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_inbox_snapshots_user_id'), table_name='inbox_snapshots')
    op.drop_table('inbox_snapshots')
    op.drop_index(op.f('ix_gmail_accounts_user_id'), table_name='gmail_accounts')
    op.drop_table('gmail_accounts')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
